name: splines
channels:
  - conda-forge
  - defaults
dependencies:
  - eigen
  - python
  - pybind11
  - pytest
  - numpy
  - pandas
  - pytest-regressions
  - coverage
  - pytest-cpp
  - boost-cpp
  - black
  - clang-format
