name: splines
channels:
  - defaults
  - conda-forge
dependencies:
  - eigen
  - python=3.9
  - pybind11
  - pytest
  - numpy
  - pandas
  - pytest-regressions
  - coverage
  - pytest-cpp
  - boost-cpp