name: linux

on: push

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++-9
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: splines
          environment-file: environment.yml
      - name: build
        env:
          CXX: g++-9
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
      - name: tests
        run: |
          coverage run -m pytest build/artifacts/
          coverage report
          
