name: windows

on:
  push:
    branches:
      - master

  pull_request:

  schedule:
    - cron: "0 5 * * 0" # Runs every Sunday at 05:00 UTC

jobs:
  ubuntu:
    name: Windows Release
    runs-on: "windows-latest"
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: splines
          environment-file: environment.yml
      - uses: microsoft/setup-msbuild@v1.0.2
      - name: build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
      - name: tests
        run: |
          coverage run -m pytest build/artifacts/
          coverage report
          
